### PR TITLE
补充语音单聊前缀判断过滤

### PR DESCRIPTION
**Pull request by zwssunny**
解决语音单聊的bug

### CODE REVIEW

**Comment by lanvent** [comment]
感谢PR!

**Comment by Nihility-Ming** [comment]
用了Railway部署后，语音mp3发不到微信上去了，卡在了这里：
[INFO][2023-03-28 19:48:17][openai_voice.py:25] - [Openai] voiceToText text=你好 voice file name=tmp/230328-194814.wav
[INFO][2023-03-28 19:48:17][wechat_channel.py:301] - [WX]receive voice, checkprefix didn't match

试过了google和baidu的语音合成都不成功

**Comment by zwssunny** [comment]
[INFO][2023-03-28 19:48:17][wechat_channel.py:301] - [WX]receive voice, checkprefix didn't match
这句已经提示，没有识别到的前缀词，建议在config.json中设置点中文前缀，方便识别
"single_chat_prefix": ["bot", "@bot","小智同学","小子同学","小志同学","小智","小子","小志"], 
 "group_chat_prefix": ["@bot","bot","小智同学","小子同学","小志同学","小智","小子","小志"],

**Comment by Nihility-Ming** [comment]
> [INFO][2023-03-28 19:48:17][wechat_channel.py:301] - [WX]receive voice, checkprefix didn't match 这句已经提示，没有识别到的前缀词，建议在config.json中设置点中文前缀，方便识别 "single_chat_prefix": ["bot", "@bot","小智同学","小子同学","小志同学","小智","小子","小志"], "group_chat_prefix": ["@bot","bot","小智同学","小子同学","小志同学","小智","小子","小志"],

解决了，感谢，群聊前缀是很有必要，但是感觉私聊还要加前缀就没必要了。。。

**Comment by Nihility-Ming** [comment]
> [INFO][2023-03-28 19:48:17][wechat_channel.py:301] - [WX]receive voice, checkprefix didn't match 这句已经提示，没有识别到的前缀词，建议在config.json中设置点中文前缀，方便识别 "single_chat_prefix": ["bot", "@bot","小智同学","小子同学","小志同学","小智","小子","小志"], "group_chat_prefix": ["@bot","bot","小智同学","小子同学","小志同学","小智","小子","小志"],

解决了，感谢，群聊前缀是很有必要，但是感觉私聊还要加前缀就没必要了，现在"single_chat_prefix": [""]时无法识别语音并弹出[WX]receive voice, checkprefix didn't match 这句，恐怕是个bug？因为纯文本聊天是没问题的，以前是没问题的，望审查代码

**Comment by lanvent** [comment]
@Nihility-Ming 抱歉，已修复，现在会检查前缀并去掉，但仍然继续处理。 （PS: 语音识别确实效果很差）

**Pull request merged**
