### PR TITLE
增加 elevent voice

### PR DESCRIPTION
**Pull request by mari1995**
增加 elevent voice

### CODE REVIEW

**Comment by cgnannan** [comment]
> 增加 elevent voice

大佬，在官方的[API Reference](https://docs.elevenlabs.io/api-reference/text-to-speech)里看到，请求时可以选voice_id,是不是把下面这段代码merge到您的elevent_voice.py里就可以了？

CHUNK_SIZE = 1024
url = "https://api.elevenlabs.io/v1/text-to-speech/<voice-id>"

headers = {
  "Accept": "audio/mpeg",
  "Content-Type": "application/json",
  "xi-api-key": "<xi-api-key>"
}

data = {
  "text": "Hi! My name is Bella, nice to meet you!",
  "model_id": "eleven_monolingual_v1",
  "voice_settings": {
    "stability": 0,
    "similarity_boost": 0
  }
}

response = requests.post(url, json=data, headers=headers)
with open('output.mp3', 'wb') as f:
    for chunk in response.iter_content(chunk_size=CHUNK_SIZE):
        if chunk:
            f.write(chunk)

**Comment by cgnannan** [comment]
> 增加 elevent voice

大佬，测试的过程中发现，抛出字符超限错误，应该是ElevenLabs给非注册用户的字符限制。这是否意味着，要突破他的字符限制，不得不在请求前，输入ElevenLabs的xi-api-key？

[INFO][2023-05-16 19:26:57][openai_voice.py:25] - [Openai] voiceToText text=Hi, is there any interesting themes that you can share with me? voice file name=tmp/230516-192655.wav
[INFO][2023-05-16 19:26:58][chat_gpt_bot.py:49] - [CHATGPT] query=Hi, is there any interesting themes that you can share with me?
[ERROR][2023-05-16 19:27:14][chat_channel.py:267] - Worker return exception: This request's text has 769 characters and exceeds the character limit of 333 characters for non signed in accounts.
Traceback (most recent call last):
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\Fort\WechatBot\chatgpt-on-wechat\channel\chat_channel.py", line 149, in _handle
    reply = self._decorate_reply(context, reply)
  File "E:\Fort\WechatBot\chatgpt-on-wechat\channel\chat_channel.py", line 219, in _decorate_reply
    reply = super().build_text_to_voice(reply.content)
  File "E:\Fort\WechatBot\chatgpt-on-wechat\channel\channel.py", line 43, in build_text_to_voice
    return Bridge().fetch_text_to_voice(text)
  File "E:\Fort\WechatBot\chatgpt-on-wechat\bridge\bridge.py", line 51, in fetch_text_to_voice
    return self.get_bot("text_to_voice").textToVoice(text)
  File "E:\Fort\WechatBot\chatgpt-on-wechat\voice\elevent\elevent_voice.py", line 24, in textToVoice
    audio = generate(
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\simple.py", line 128, in generate
    return TTS.generate(text, voice, model)
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\api\tts.py", line 19, in generate
    response = API.post(url, json=data)
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\api\base.py", line 65, in post
    return API.request(url, method="post", *args, **kwargs)  # type: ignore
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\api\base.py", line 57, in request
    raise APIError(error)
elevenlabs.api.error.APIError: This request's text has 769 characters and exceeds the character limit of 333 characters for non signed in accounts.

**Comment by cgnannan** [comment]
> > 增加 elevent voice
> 
> 大佬，测试的过程中发现，抛出字符超限错误，应该是ElevenLabs给非注册用户的字符限制。这是否意味着，要突破他的字符限制，不得不在请求前，输入ElevenLabs的xi-api-key？
> 
> [INFO][2023-05-16 19:26:57][openai_voice.py:25] - [Openai] voiceToText text=Hi, is there any interesting themes that you can share with me? voice file name=tmp/230516-192655.wav [INFO][2023-05-16 19:26:58][chat_gpt_bot.py:49] - [CHATGPT] query=Hi, is there any interesting themes that you can share with me? [ERROR][2023-05-16 19:27:14][chat_channel.py:267] - Worker return exception: This request's text has 769 characters and exceeds the character limit of 333 characters for non signed in accounts. Traceback (most recent call last): File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "E:\Fort\WechatBot\chatgpt-on-wechat\channel\chat_channel.py", line 149, in _handle reply = self._decorate_reply(context, reply) File "E:\Fort\WechatBot\chatgpt-on-wechat\channel\chat_channel.py", line 219, in _decorate_reply reply = super().build_text_to_voice(reply.content) File "E:\Fort\WechatBot\chatgpt-on-wechat\channel\channel.py", line 43, in build_text_to_voice return Bridge().fetch_text_to_voice(text) File "E:\Fort\WechatBot\chatgpt-on-wechat\bridge\bridge.py", line 51, in fetch_text_to_voice return self.get_bot("text_to_voice").textToVoice(text) File "E:\Fort\WechatBot\chatgpt-on-wechat\voice\elevent\elevent_voice.py", line 24, in textToVoice audio = generate( File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\simple.py", line 128, in generate return TTS.generate(text, voice, model) File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\api\tts.py", line 19, in generate response = API.post(url, json=data) File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\api\base.py", line 65, in post return API.request(url, method="post", *args, **kwargs) # type: ignore File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\elevenlabs\api\base.py", line 57, in request raise APIError(error) elevenlabs.api.error.APIError: This request's text has 769 characters and exceeds the character limit of 333 characters for non signed in accounts.

大佬，我根据ElevenLabs官方的API Document，在您的代码上做了点微调。测试后，可以通过填写<xi-api-key>和对应的<voice-id>选择11Labs提供的不同声音，也能突破请求时的字符限制。限于我还是个代码菜鸟，还需要反复测试，看看是否有其他bug，所以目前还不敢提PR或merge。另外，代码也没有留出来外置的config.json模板(不会弄)，希望大佬多多指教。

import time
import requests

from bridge.reply import Reply, ReplyType
from common.log import logger
from common.tmp_dir import TmpDir
from voice.voice import Voice


class ElevenLabsVoice(Voice):
    def __init__(self):
        pass

    def voiceToText(self, voice_file):
        pass

    def textToVoice(self, text):
        url = "https://api.elevenlabs.io/v1/text-to-speech/<voice-id>"
        headers = {
            "Accept": "audio/mpeg",
            "Content-Type": "application/json",
            "xi-api-key": "<xi-api-key>"
        }
        data = {
            "text": text,
            "model_id": "eleven_monolingual_v1",
            "voice_settings": {
                "stability": 0,
                "similarity_boost": 0
            }
        }
        response = requests.post(url, json=data, headers=headers)
        audio = response.content
        fileName = TmpDir().path() + "reply-" + str(int(time.time())) + "-" + str(hash(text) & 0x7FFFFFFF) + ".mp3"
        with open(fileName, "wb") as f:
            f.write(audio)
        logger.info("[ElevenLabs] textToVoice text={} voice file name={}".format(text, fileName))
        return Reply(ReplyType.VOICE, fileName)

**Comment by zhayujie** [comment]
elevenLabs目前已经有了， 还是感谢PR哈~

**Pull request closed without merging**
