### PR TITLE
钉钉机器人

### PR DESCRIPTION
**Pull request by huiwenTT**
增加钉钉机器人，支持Stream模式

### CODE REVIEW

**Comment by zhayujie** [comment]
感谢pr，我们来是试一下

**Comment by 6vision** [comment]
老哥，我这边服务器运行后，stream可以接通，但私聊和群聊，服务器都收不到消息哎，有什么特别注意的么？

**Comment by huiwenTT** [comment]
> 老哥，我这边服务器运行后，stream可以接通，但私聊和群聊，服务器都收不到消息哎，有什么特别注意的么？

配置文件，配置了吗

**Comment by 6vision** [comment]
> > 老哥，我这边服务器运行后，stream可以接通，但私聊和群聊，服务器都收不到消息哎，有什么特别注意的么？
> 
> 配置文件，配置了吗

app id和app secret 两个参数，
在钉钉后台点连通性测试，显示通，log也显示有消息

**Comment by huiwenTT** [comment]
> > > 老哥，我这边服务器运行后，stream可以接通，但私聊和群聊，服务器都收不到消息哎，有什么特别注意的么？
> 
> > 
> 
> > 配置文件，配置了吗
> 
> 
> 
> app id和app secret 两个参数，
> 
> 在钉钉后台点连通性测试，显示通，log也显示有消息

我刚测了下，钉钉接口有点变化，我一会重提一次

**Comment by huiwenTT** [comment]
> > > 老哥，我这边服务器运行后，stream可以接通，但私聊和群聊，服务器都收不到消息哎，有什么特别注意的么？
> 
> > 
> 
> > 配置文件，配置了吗
> 
> 
> 
> app id和app secret 两个参数，
> 
> 在钉钉后台点连通性测试，显示通，log也显示有消息

重新提交了，有劳了

**Comment by tengzhaoyong** [comment]
接入钉钉后，启动报以下错误，certifi 也安装了，python3.8版本环境：
2023-12-24 20:51:45,648 dingtalk_stream.client INFO     open connection, url=https://api.dingtalk.com/v1.0/gateway/connections/open [stream.py:133]
2023-12-24 20:51:45,814 dingtalk_stream.client INFO     endpoint is {'endpoint': 'wss://wss-open-connection.dingtalk.com:443/connect', 'ticket': '31e54f1e-a25b-11ee-8ef4-6e1e6cb7263c'} [stream.py:72]
^C[INFO][2023-12-24 20:51:46][app.py:20] - signal 2 received, exiting...
[INFO][2023-12-24 20:51:46][config.py:208] - [Config] User datas saved.
Traceback (most recent call last):
  File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 119, in start_forever
    asyncio.run(self.start())
  File "/usr/local/python-3.8.16/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 75, in start
    async with websockets.connect(uri) as websocket:
  File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
  File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python-3.8.16/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

**Review by zhayujie — APPROVED** [review]

**Comment by zhayujie** [comment]
thanks for pr~

**Comment by huiwenTT** [comment]
> 接入钉钉后，启动报以下错误，certifi 也安装了，python3.8版本环境：
> 
> 2023-12-24 20:51:45,648 dingtalk_stream.client INFO     open connection, url=https://api.dingtalk.com/v1.0/gateway/connections/open [stream.py:133]
> 
> 2023-12-24 20:51:45,814 dingtalk_stream.client INFO     endpoint is {'endpoint': 'wss://wss-open-connection.dingtalk.com:443/connect', 'ticket': '31e54f1e-a25b-11ee-8ef4-6e1e6cb7263c'} [stream.py:72]
> 
> ^C[INFO][2023-12-24 20:51:46][app.py:20] - signal 2 received, exiting...
> 
> [INFO][2023-12-24 20:51:46][config.py:208] - [Config] User datas saved.
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 119, in start_forever
> 
>     asyncio.run(self.start())
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/asyncio/runners.py", line 44, in run
> 
>     return loop.run_until_complete(main)
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
> 
>     return future.result()
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 75, in start
> 
>     async with websockets.connect(uri) as websocket:
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 629, in __aenter__
> 
>     return await self
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
> 
>     return await self.__await_impl__()
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
> 
>     _transport, _protocol = await self._create_connection()
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
> 
>     transport, protocol = await self._create_connection_transport(
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
> 
>     await waiter
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
> 
>     ssldata, appdata = self._sslpipe.feed_ssldata(data)
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
> 
>     self._sslobj.do_handshake()
> 
>   File "/usr/local/python-3.8.16/lib/python3.8/ssl.py", line 944, in do_handshake
> 
>     self._sslobj.do_handshake()
> 
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

这个是环境问题，我之前也遇到过，是因为钉钉在建立链接的时候，必须用 openssl 1.1.1 以上版本，要更新 Python 对应的 openssl 版本，而且在虚拟机中也不行。

**Comment by tengzhaoyong** [comment]
> > 接入钉钉后，启动报以下错误，certifi 也安装了，python3.8版本环境：
> > 2023-12-24 20:51:45,648 dingtalk_stream.client INFO     open connection, url=https://api.dingtalk.com/v1.0/gateway/connections/open [stream.py:133]
> > 2023-12-24 20:51:45,814 dingtalk_stream.client INFO     endpoint is {'endpoint': 'wss://wss-open-connection.dingtalk.com:443/connect', 'ticket': '31e54f1e-a25b-11ee-8ef4-6e1e6cb7263c'} [stream.py:72]
> > ^C[INFO][2023-12-24 20:51:46][app.py:20] - signal 2 received, exiting...
> > [INFO][2023-12-24 20:51:46][config.py:208] - [Config] User datas saved.
> > Traceback (most recent call last):
> > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 119, in start_forever
> > ```
> > asyncio.run(self.start())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/runners.py", line 44, in run
> > ```
> > return loop.run_until_complete(main)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
> > ```
> > return future.result()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 75, in start
> > ```
> > async with websockets.connect(uri) as websocket:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 629, in **aenter**
> > ```
> > return await self
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 647, in **await_impl_timeout**
> > ```
> > return await self.__await_impl__()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 651, in **await_impl**
> > ```
> > _transport, _protocol = await self._create_connection()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
> > ```
> > transport, protocol = await self._create_connection_transport(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
> > ```
> > await waiter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
> > ```
> > ssldata, appdata = self._sslpipe.feed_ssldata(data)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
> > ```
> > self._sslobj.do_handshake()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/local/python-3.8.16/lib/python3.8/ssl.py", line 944, in do_handshake
> > ```
> > self._sslobj.do_handshake()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
> 
> 这个是环境问题，我之前也遇到过，是因为钉钉在建立链接的时候，必须用 openssl 1.1.1 以上版本，要更新 Python 对应的 openssl 版本，而且在虚拟机中也不行。

那是打成docker么？用的基础镜像是什么呢？或者用的docker build命令方便分享下么？

**Comment by huiwenTT** [comment]
> > > 接入钉钉后，启动报以下错误，certifi 也安装了，python3.8版本环境：
> 
> > > 2023-12-24 20:51:45,648 dingtalk_stream.client INFO     open connection, url=https://api.dingtalk.com/v1.0/gateway/connections/open [stream.py:133]
> 
> > > 2023-12-24 20:51:45,814 dingtalk_stream.client INFO     endpoint is {'endpoint': 'wss://wss-open-connection.dingtalk.com:443/connect', 'ticket': '31e54f1e-a25b-11ee-8ef4-6e1e6cb7263c'} [stream.py:72]
> 
> > > ^C[INFO][2023-12-24 20:51:46][app.py:20] - signal 2 received, exiting...
> 
> > > [INFO][2023-12-24 20:51:46][config.py:208] - [Config] User datas saved.
> 
> > > Traceback (most recent call last):
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 119, in start_forever
> 
> > > ```
> 
> > > asyncio.run(self.start())
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/runners.py", line 44, in run
> 
> > > ```
> 
> > > return loop.run_until_complete(main)
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
> 
> > > ```
> 
> > > return future.result()
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/dingtalk_stream/stream.py", line 75, in start
> 
> > > ```
> 
> > > async with websockets.connect(uri) as websocket:
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 629, in **aenter**
> 
> > > ```
> 
> > > return await self
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 647, in **await_impl_timeout**
> 
> > > ```
> 
> > > return await self.__await_impl__()
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/site-packages/websockets/legacy/client.py", line 651, in **await_impl**
> 
> > > ```
> 
> > > _transport, _protocol = await self._create_connection()
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
> 
> > > ```
> 
> > > transport, protocol = await self._create_connection_transport(
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
> 
> > > ```
> 
> > > await waiter
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
> 
> > > ```
> 
> > > ssldata, appdata = self._sslpipe.feed_ssldata(data)
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
> 
> > > ```
> 
> > > self._sslobj.do_handshake()
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > File "/usr/local/python-3.8.16/lib/python3.8/ssl.py", line 944, in do_handshake
> 
> > > ```
> 
> > > self._sslobj.do_handshake()
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
> 
> > 
> 
> > 这个是环境问题，我之前也遇到过，是因为钉钉在建立链接的时候，必须用 openssl 1.1.1 以上版本，要更新 Python 对应的 openssl 版本，而且在虚拟机中也不行。
> 
> 
> 
> 那是打成docker么？用的基础镜像是什么呢？或者用的docker build命令方便分享下么？
> 
> 用 Python3.9的镜像，直接build

**Comment by adminlove520** [comment]
请问 钉钉这个可以做成 流式输出吗
https://open.dingtalk.com/document/orgapp/typewriter-effect-streaming-ai-card
然后就是 现在好像是text的  对于像表格这种就会格式很乱  可以改成markdown嘛 @huiwenTT @zhayujie

**Comment by terry-job-data** [comment]
I got this problem , how can I fix it ? 
2024-06-02 02:56:00,549 dingtalk_stream.client WARNING  unknown message topic, topic=ping, message={'specVersion': '1.0', 'type': 'SYSTEM', 'headers': {'appId': '970cde03-04ad-4392-9071-d5ebbb5b5941', 'connectionId': '653ad77c-2048-11ef-86c6-72d2a0cf873e', 'contentType': 'application/json', 'messageId': '213dee76_f85_18fbdfc4f12_2d2ec5', 'time': '1717268160800', 'topic': 'ping'}, 'data': '{"opaque":"3e304572-5400-4804-8d33-4bea34d87935"}'} [stream.py:96]

**Comment by huiwenTT** [comment]
可以，之后版本更新

**Comment by huiwenTT** [comment]
这好像是个警告，现在可以正常使用吗

**Pull request merged**
