### PR TITLE
Update claude_ai_bot.py

### PR DESCRIPTION
**Pull request by resphinas**
1.修复claude_uuid指定对话功能
2.删除冗余代码
3.增加 ip被ban、cookie验证失败、速率限制 相关容错提示
已测试

### CODE REVIEW

**Comment by fatwang2** [comment]
测试了下，终于可以了！感谢

**Review by zhayujie — APPROVED** [review]

**Comment by zhayujie** [comment]
thanks for pr

**Comment by jjyyfff** [comment]
一个合规的cookie长啥样？我这个对吗？

image

**Comment by resphinas** [comment]
image
这个cookie 的值全部复制下来

**Comment by jjyyfff** [comment]
ok，目前配置如下，可有错？谢谢

dc16f6fe9135ebbd8e133e56d28f90f

**Comment by resphinas** [comment]
> ok，目前配置如下，可有错？谢谢
> 
> dc16f6fe9135ebbd8e133e56d28f90f

目测无

**Comment by jjyyfff** [comment]
[ERROR][2023-09-04 11:25:02][chat_channel.py:280] - Worker return exception: local variable 'response' referenced before assignment

curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\cacert.pem CApath: none'

运行后两个错误。

环境：windows，个人微信，私聊，“你是谁”

**Comment by resphinas** [comment]
麻烦复制下完整报错

**Comment by jjyyfff** [comment]
Loading the contact, this may take a little while.
Login successfully as 小助手
[INFO][2023-09-04 11:24:42][wechat_channel.py:126] - Wechat login success, user_id: @7e7abbfd85f24d4f4c43eaccde44d2e1ce8c152c4146ced2e0fb91f88dc269b2, nickname: 小助手
Start auto replying.
[INFO][2023-09-04 11:25:01][bridge.py:38] - create bot claude for chat
[ERROR][2023-09-04 11:25:02][chat_channel.py:280] - Worker return exception: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\requests\session.py", line 436, in request
    c.perform()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\curl.py", line 191, in perform
    self._check_error(ret, action="perform")
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\curl.py", line 84, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\蒋迎锋\AppData\Local\Programs\Python\Python310\lib\s
ite-packages\curl_cffi\cacert.pem CApath: none'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\weRobot\助手-chatgpt-on-wechat\bot\claude\claude_ai_bot.py", line 68, in get_organization_id
    response = requests.get(url, headers=headers, impersonate="chrome110", proxies =self.proxies, timeout=400)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\requests\__init__.py", line 46, in request
    return s.request(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\requests\session.py", line 438, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\xxx\AppData\Local\Programs\Python\
Python310\lib\site-packages\curl_cffi\cacert.pem CApath: none'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\weRobot\助手-chatgpt-on-wechat\channel\chat_channel.py", line 155, in _handle
    reply = self._generate_reply(context)
  File "C:\weRobot\助手-chatgpt-on-wechat\channel\chat_channel.py", line 177, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "C:\weRobot\助手-chatgpt-on-wechat\channel\channel.py", line 37, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "C:\weRobot\助手-chatgpt-on-wechat\bridge\bridge.py", line 53, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "C:\weRobot\助手-chatgpt-on-wechat\bridge\bridge.py", line 44, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "C:\weRobot\助手-chatgpt-on-wechat\bot\bot_factory.py", line 45, in create_bot
    return ClaudeAIBot()
  File "C:\weRobot\助手-chatgpt-on-wechat\bot\claude\claude_ai_bot.py", line 31, in __init__
    self.org_uuid = self.get_organization_id()
  File "C:\weRobot\助手-chatgpt-on-wechat\bot\claude\claude_ai_bot.py", line 72, in get_organization_id
    if "App unavailable" in response.text:
UnboundLocalError: local variable 'response' referenced before assignment

完整报错如上。已重启

**Comment by resphinas** [comment]
> Loading the contact, this may take a little while. Login successfully as 小助手 [INFO][2023-09-04 11:24:42][wechat_channel.py:126] - Wechat login success, user_id: @7e7abbfd85f24d4f4c43eaccde44d2e1ce8c152c4146ced2e0fb91f88dc269b2, nickname: 小助手 Start auto replying. [INFO][2023-09-04 11:25:01][bridge.py:38] - create bot claude for chat [ERROR][2023-09-04 11:25:02][chat_channel.py:280] - Worker return exception: local variable 'response' referenced before assignment Traceback (most recent call last): File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\requests\session.py", line 436, in request c.perform() File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\curl.py", line 191, in perform self._check_error(ret, action="perform") File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\curl.py", line 84, in _check_error raise error curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations: CAfile: C:\Users\蒋迎锋\AppData\Local\Programs\Python\Python310\lib\s ite-packages\curl_cffi\cacert.pem CApath: none'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\weRobot\助手-chatgpt-on-wechat\bot\claude\claude_ai_bot.py", line 68, in get_organization_id response = requests.get(url, headers=headers, impersonate="chrome110", proxies =self.proxies, timeout=400) File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\requests__init__.py", line 46, in request return s.request( File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\requests\session.py", line 438, in request raise RequestsError(e) curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations: CAfile: C:\Users\xxx\AppData\Local\Programs\Python Python310\lib\site-packages\curl_cffi\cacert.pem CApath: none'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "C:\weRobot\助手-chatgpt-on-wechat\channel\chat_channel.py", line 155, in _handle reply = self._generate_reply(context) File "C:\weRobot\助手-chatgpt-on-wechat\channel\chat_channel.py", line 177, in _generate_reply reply = super().build_reply_content(context.content, context) File "C:\weRobot\助手-chatgpt-on-wechat\channel\channel.py", line 37, in build_reply_content return Bridge().fetch_reply_content(query, context) File "C:\weRobot\助手-chatgpt-on-wechat\bridge\bridge.py", line 53, in fetch_reply_content return self.get_bot("chat").reply(query, context) File "C:\weRobot\助手-chatgpt-on-wechat\bridge\bridge.py", line 44, in get_bot self.bots[typename] = create_bot(self.btype[typename]) File "C:\weRobot\助手-chatgpt-on-wechat\bot\bot_factory.py", line 45, in create_bot return ClaudeAIBot() File "C:\weRobot\助手-chatgpt-on-wechat\bot\claude\claude_ai_bot.py", line 31, in **init** self.org_uuid = self.get_organization_id() File "C:\weRobot\助手-chatgpt-on-wechat\bot\claude\claude_ai_bot.py", line 72, in get_organization_id if "App unavailable" in response.text: UnboundLocalError: local variable 'response' referenced before assignment
> 
> 完整报错如上。已重启

curl_cffi 版本是什么

**Comment by jjyyfff** [comment]
兄弟，名字x掉，抱歉哈

**Comment by jjyyfff** [comment]
image

**Comment by resphinas** [comment]
外部原因不好复现 可以基于“curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations: CAfile:”字段查阅下相关资料整改（如https://github.com/yifeikong/curl_cffi/issues/104），解决了欢迎分享一下

**Comment by jjyyfff** [comment]
兄弟，帮手把你引用的故障里出现的 名字 叉掉，多谢哈

**Comment by resphinas** [comment]
image
也许是xxzdgoi下载过程中损坏或者下载源有问题？用这个命令强制重新下  然后可以试试不同的源 `pip install curl_cffi  --upgrade --force-reinstall --no-cache-dir `

**Comment by jjyyfff** [comment]
已按这个直接下载了证书：https://github.com/yifeikong/curl_cffi/issues/104，其次，也强制重装了 pip install curl_cffi  --upgrade --force-reinstall --no-cache-dir。

目前看，故障依旧。

中文这个。。。。有点头疼了，管理员号得改名字。

虚拟这个。。。。谢谢哈

**Comment by resphinas** [comment]
> 已按这个直接下载了证书：[https://github.com/yifeikong/curl_cffi/issues/104，其次，也强制重装了](https://github.com/yifeikong/curl_cffi/issues/104%EF%BC%8C%E5%85%B6%E6%AC%A1%EF%BC%8C%E4%B9%9F%E5%BC%BA%E5%88%B6%E9%87%8D%E8%A3%85%E4%BA%86) pip install curl_cffi --upgrade --force-reinstall --no-cache-dir。
> 
> 目前看，故障依旧。
> 
> 中文这个。。。。有点头疼了，管理员号得改名字。
> 
> 虚拟这个。。。。谢谢哈

虚拟环境就可以规避不修改管理员名字

**Comment by jjyyfff** [comment]
image

**Comment by resphinas** [comment]
image
scripts的s大写

**Comment by jjyyfff** [comment]
image

**Comment by resphinas** [comment]
image
这个运行过了嘛

**Comment by jjyyfff** [comment]
是啊

**Comment by resphinas** [comment]
> 是啊

...给我干沉默了

**Comment by jjyyfff** [comment]
兄弟，我总觉得我的cookie有问题，可否私信你我的 cookie 试试？

**Comment by resphinas** [comment]
> 兄弟，我总觉得我的cookie有问题，可否私信你我的 cookie 试试？

这报错跟cookie没关系，cookie有问题会有正常的提示不会报错

**Comment by jjyyfff** [comment]
若 cookie 没问题，才有动力折腾，帮我确认下？

**Comment by resphinas** [comment]
代码我写的啊跟cookie没关系相信我0.o！

**Comment by jjyyfff** [comment]
可是我没在 claude 官网注册过啊

**Comment by resphinas** [comment]
> 代码我写的啊跟cookie没关系相信我0.o！

你这报错都不是项目的原因，环境问题

**Comment by jjyyfff** [comment]
> > 代码我写的啊跟cookie没关系相信我0.o！
> 
> 你这报错都不是项目的原因，环境问题

有点晕。。。。我歇会，抽支烟

**Comment by resphinas** [comment]
邮箱发我向日葵  给你诊诊脉

**Comment by jjyyfff** [comment]
> 邮箱发我向日葵 给你诊诊脉 [2934218525@qq.com](mailto:2934218525@qq.com)

已经给你发了邮件。。。。

**Comment by resphinas** [comment]
> [ERROR][2023-09-04 11:25:02][chat_channel.py:280] - Worker return exception: local variable 'response' referenced before assignment
> 
> curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations: CAfile: C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\cacert.pem CApath: none'
> 
> 运行后两个错误。
> 
> 环境：删除了uuid。windows，个人微信，私聊，“你是谁”

curl_cffi包所在目录中不能存在中文
1.修改一切出现在报错中的中文为英文
2.重新采用 python -m venv venv 创建全新英文目录环境

**Comment by jjyyfff** [comment]
> > [ERROR][2023-09-04 11:25:02][chat_channel.py:280] - Worker return exception: local variable 'response' referenced before assignment
> > curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations: CAfile: C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\cacert.pem CApath: none'
> > 运行后两个错误。
> > 环境：删除了uuid。windows，个人微信，私聊，“你是谁”
> 
> curl_cffi包所在目录中不能存在中文 1.修改一切出现在报错中的中文为英文 2.重新采用 python -m venv venv 创建全新英文目录环境

非常感谢，定位准确，问题解决！

**Pull request merged**
