### PR TITLE
add wechaty

### PR DESCRIPTION
**Pull request by ZQ7**

### CODE REVIEW

**Comment by ZQ7** [comment]
add [python-wechaty](https://wechaty.readthedocs.io/zh_CN/latest/)
channel = channel_factory.create_channel("wxy")

**Review by zhayujie — APPROVED** [review]

**Comment by ZQ7** [comment]
Pad协议教程

1. [pad-local](http://pad-local.com/) 获取PadLocal Token
2. Python随机生成UUID：
import uuid;
print(uuid.uuid4());
3. Docker容器部署Padlocal网关服务(代码在最下方，替换
WECHATY_PUPPET_PADLOCAL_TOKEN 和 WECHATY_TOKEN为实际值)
4. 将uuid配置在config.json(对应KEY:wechaty_puppet_service_token)
5. 修改启动文件app.py
channel = channel_factory.create_channel("wxy")

```
# 设置环境变量
export WECHATY_LOG="verbose"
export WECHATY_PUPPET="wechaty-puppet-padlocal"
# PadLocal Token
export WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal_xxx"

export WECHATY_PUPPET_SERVER_PORT="9001"
# 可使用代码随机生成UUID：import uuid;print(uuid.uuid4());
export WECHATY_TOKEN="d671a197-71c9-4ca6-a673-xxxxxx"
# 由于版本细节问题，目前python-wechaty 支持最好的wechaty镜像为：[wechaty/wechaty:0.65](https://hub.docker.com/layers/wechaty/wechaty/0.65/images/sha256-d39b9fb5dece3a8ffa88b80a8ccfd916be14b9d0de72115732c3ee714b0d6a96?context=explore)
docker run -ti \
  --name wechaty_puppet_service_token_gateway \
  --rm \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_PADLOCAL_TOKEN \
  -e WECHATY_PUPPET_SERVER_PORT \
  -e WECHATY_TOKEN \
  -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
  wechaty/wechaty:0.65
```

**Comment by isbase** [comment]
要扫码2次吗， 我docker 运行，这个wechaty ok ，但是运行chatgpt-on-wechat 还需要扫码一次？

**Comment by isbase** [comment]
f"can't not ping endpoint: {self.options.end_point}"
wechaty_puppet.exceptions.WechatyPuppetConfigurationError: WechatyPuppetConfigurationError("can't not ping endpoint: 124.78.247.12:9001", None, None)

哥哥们，这个显示外网IP，咋处理呢

**Comment by ZQ7** [comment]
体验微信二维码
WechatIMG281

**Comment by tryao** [comment]
可以在本地运行吗？

**Comment by tryao** [comment]
> 可以在本地运行吗？

我执行Python3 app.py没有生成二维码

**Comment by Tianket** [comment]
按照您的方法，使用注册一周的微信小号，用pad-local刚登陆就封号了，可能是我微信注册时间短的问题，给大家避个雷

**Comment by ZQ7** [comment]
> 按照您的方法，使用注册一周的微信小号，用pad-local刚登陆就封号了，可能是我微信注册时间短的问题，给大家避个雷

肯定都有风险，付费的相对好一点

**Comment by ZQ7** [comment]
> > 可以在本地运行吗？
> 
> 我执行Python3 app.py没有生成二维码

可以本地，执行有报错吗

**Comment by zzh2524338** [comment]
本地运行Wechaty - ERROR - The network is not good, the bot will try to restart after 60 seconds.

**Comment by YZHsir** [comment]
~~~
[ERROR][2023-02-26 15:45:24][app.py:20] - App startup failed!
[ERROR][2023-02-26 15:45:24][app.py:21] - No module named 'wechaty_puppet'
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    channel = channel_factory.create_channel("wxy")
  File "/root/chatgpt-on-wechat/channel/channel_factory.py", line 15, in create_channel
    from channel.wechat.wechaty_channel import WechatyChannel
  File "/root/chatgpt-on-wechat/channel/wechat/wechaty_channel.py", line 14, in <module>
    from wechaty_puppet import MessageType, FileBox, ScanStatus  # type: ignore
ModuleNotFoundError: No module named 'wechaty_puppet'
~~~
**大佬，为啥我的会报这个错**

**Comment by baimingl** [comment]
现在用着怎么样？还会被封吗

**Comment by Foristkirito** [comment]
image
抱着个错啥原因？

**Comment by HiJackXD** [comment]
我用的WSL启动的docker，微信也登录成功了，pad-loca上也显示token在线。
但是https://api.chatie.io/v0/hosties/puppet_padlocal_xxxx 显示都是0，导致py启动报错

```shell
2023-03-02 14:57:41,244 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/puppet_padlocal_******
Traceback (most recent call last):
  File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty\wechaty.py", line 445, in start
    await self.puppet.start()
  File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 911, in start
    self._init_puppet()
  File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 876, in _init_puppet
    raise WechatyPuppetGrpcError(
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)

```

**Comment by baimingl** [comment]
已经放弃了，改用web版了

**Comment by lipc2** [comment]
Docker容器部署Padlocal网关服务，这块有具体的操作步骤吗？辛苦老哥捞一下

**Comment by emmmnaadada** [comment]
> 我用的WSL启动的docker，微信也登录成功了，pad-loca上也显示token在线。 但是是https://api.chatie.io/v0/hosties/puppet_padlocal_xxxx显示都是0，导致py启动报错
> 
> ```shell
> 2023-03-02 14:57:41,244 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/puppet_padlocal_******
> Traceback (most recent call last):
>   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty\wechaty.py", line 445, in start
>     await self.puppet.start()
>   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 911, in start
>     self._init_puppet()
>   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 876, in _init_puppet
>     raise WechatyPuppetGrpcError(
> wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)
> ```
> 
> 解决了得公网ip

同样的问题怎么解决的

**Comment by wantiedaishu** [comment]
> 我用的WSL启动的docker，微信也登录成功了，pad-loca上也显示token在线。 但是https://api.chatie.io/v0/hosties/puppet_padlocal_xxxx 显示都是0，导致py启动报错
> 
> ```shell
> 2023-03-02 14:57:41,244 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/puppet_padlocal_******
> Traceback (most recent call last):
>   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty\wechaty.py", line 445, in start
>     await self.puppet.start()
>   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 911, in start
>     self._init_puppet()
>   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 876, in _init_puppet
>     raise WechatyPuppetGrpcError(
> wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)
> ```
> 
> 解决了 得公网ip

我也遇到这个问题

**Comment by qijia2045579** [comment]
https://github.com/wechaty/python-wechaty-puppet-service/blob/5174faf061ea705dc887d615f1268a8c5d4b886a/src/wechaty_puppet_service/puppet.py#L873

**Comment by Tyler201609** [comment]
用padlocal的token，报错啊：
nohup: ignoring input and appending output to ‘nohup.out’
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-1.0.4/app.py", line 4, in <module>
    from channel import channel_factory
  File "/root/chatgpt-on-wechat-1.0.4/channel/channel_factory.py", line 13
    return WechatyChannel()
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-1.0.4/app.py", line 4, in <module>
    from channel import channel_factory
  File "/root/chatgpt-on-wechat-1.0.4/channel/channel_factory.py", line 13
    return WechatyChannel()
TabError: inconsistent use of tabs and spaces in indentation

**Comment by Tyler201609** [comment]
> 按照您的方法，使用注册一周的微信小号，用pad-local刚登陆就封号了，可能是我微信注册时间短的问题，给大家避个雷

token填写在哪儿啊，没看到啊，填写个  登录报错了

**Comment by Tyler201609** [comment]
[ERROR][2023-03-07 21:35:25][app.py:19] - App startup failed!
[ERROR][2023-03-07 21:35:25][app.py:20] - Expecting value: line 7 column 50 (char 256)
Traceback (most recent call last):
  File "/root/home/chatgpt-on-wechat-1.0.4/app.py", line 11, in <module>
    config.load_config()
  File "/root/home/chatgpt-on-wechat-1.0.4/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/home/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 50 (char 256)

怎么这个错误啊。登录不了啊 wechaty的

> Refer

[ERROR][2023-03-07 21:35:25][app.py:19] - App startup failed!
[ERROR][2023-03-07 21:35:25][app.py:20] - Expecting value: line 7 column 50 (char 256)
Traceback (most recent call last):
  File "/root/home/chatgpt-on-wechat-1.0.4/app.py", line 11, in <module>
    config.load_config()
  File "/root/home/chatgpt-on-wechat-1.0.4/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/home/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 50 (char 256)

怎么这个错误啊。登录不了啊 wechaty的

**Comment by bravedigger** [comment]
> image
> 
> 抱着个错啥原因？

我也遇到同样问题;
image
运行环境：Ubuntu 20 + Python 3.10.6

**Comment by ZQ7** [comment]
> > 我用的WSL启动的docker，微信也登录成功了，pad-loca上也显示token在线。 但是https://api.chatie.io/v0/hosties/puppet_padlocal_xxxx 显示都是0，导致py启动报错
> > ```shell
> > 2023-03-02 14:57:41,244 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/puppet_padlocal_******
> > Traceback (most recent call last):
> >   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty\wechaty.py", line 445, in start
> >     await self.puppet.start()
> >   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 911, in start
> >     self._init_puppet()
> >   File "C:\Users\yangz\AppData\Local\Programs\Python\Python310\lib\site-packages\wechaty_puppet_service\puppet.py", line 876, in _init_puppet
> >     raise WechatyPuppetGrpcError(
> > wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 解决了 得公网ip
> 
> 我也遇到这个问题

本地运行没有公网IP，需要将 os.environ['WECHATY_PUPPET_SERVICE_TOKEN'] = token 修改为 os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = "127.0.0.1:9001"

**Comment by ZQ7** [comment]
> 2\. 配置文件 config.json 内的 **wechaty_puppet_service_token** 非[pad-local](http://pad-local.com/) 获取的Token，此处的token为uuid生成的，一定要将uuid生成的token和在pad-local获取到的token部署在Docker网关内！！！！

配置文件 config.json 内的 wechaty_puppet_service_token 非[pad-local](http://pad-local.com/) 获取的Token，此处的token为uuid生成的，一定要将uuid生成的token和在pad-local获取到的token部署在Docker网关内！！！！

**Comment by chzzfly** [comment]
费用：1个月200，一年5折1200

**Comment by 1018987534** [comment]
可以登录，也可以正常运行，但是只要发送文字就报错：

**Comment by 1018987534** [comment]
2023-03-12 00:15:03,900 - Wechaty - INFO - receive message <Message#message_type_text[🗣 Contact <wxid_qi3cvez0dka911> <你的意义>       你好>
2023-03-12 00:15:03,900 - Message - INFO - Message mention_list
[ERROR][2023-03-12 00:15:03][wechaty_channel.py:136] - No module named 'openai'
Traceback (most recent call last):
  File "/work/chatGPT/chatgpt-on-wechat/channel/wechat/wechaty_channel.py", line 132, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/work/chatGPT/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/work/chatGPT/chatgpt-on-wechat/bridge/bridge.py", line 10, in fetch_reply_content
    return bot_factory.create_bot("chatGPT").reply(query, context)
  File "/work/chatGPT/chatgpt-on-wechat/bot/bot_factory.py", line 19, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "/work/chatGPT/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 7, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by 1018987534** [comment]
2023-03-12 01:09:29,914 - Wechaty - INFO - receive message <Message#message_type_audio[🗣 Contact <wxid_qi3cvez0dka911> <你的意义>>
2023-03-12 01:09:29,914 - Message - INFO - Message mention_list





发送语音后无反应

**Comment by TrickeryJoker** [comment]
> > image
> > 抱着个错啥原因？
> 
> 我也遇到同样问题; image 运行环境：Ubuntu 20 + Python 3.10.6

我也是这个错误 请问你们解决了吗

**Comment by austincityuwen** [comment]
我想请教一下，使用PadLocal协议，windows系统是否支持，还是只能用Linux?

**Comment by austincityuwen** [comment]
用padlocal协议的情况下，用docker搭建gateway服务后，主程序可以跑在windows上吗？

**Comment by HiJackXD** [comment]
> 用padlocal协议的情况下，用docker搭建gateway服务后，主程序可以跑在windows上吗？

可以 主程序只对接tcp，所以和平台无关

**Comment by austincityu** [comment]
> > > image
> > > 抱着个错啥原因？
> > 
> > 
> > 我也遇到同样问题; image 运行环境：Ubuntu 20 + Python 3.10.6
> 
> 我也是这个错误 请问你们解决了吗

我的环境是Ubuntu 20.04 + Python 3.8.6，也报这个错了。'WechatyChannel' object has no attribute 'Contact' 解决了吗？

**Comment by Bachery** [comment]
> > 
> 
> 同样报这个错，解决了么？在docker里跑wechaty没问题。
> 
> > image os.environ['WECHATY_PUPPET_SERVICE_TOKEN'] = token 修改为 os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = "127.0.0.1:9001" 本地运行报这个错
> 
> 解决了么，我也出现这个报错

我也遇到了这个报错

**Comment by kadaliao** [comment]
> > > 
> > 
> > 
> > 同样报这个错，解决了么？在docker里跑wechaty没问题。
> > > image os.environ['WECHATY_PUPPET_SERVICE_TOKEN'] = token 修改为 os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = "127.0.0.1:9001" 本地运行报这个错
> > 
> > 
> > 解决了么，我也出现这个报错
> 
> 我也遇到了这个报错

一样的问题，没解决。

wechaty 的容器、token 都是正常的。

把报错代码删了之后，，能扫码、能登录。但是不一会儿提示已退出微信又重新弹出二维码。

**Comment by aardwolf109** [comment]
> image os.environ['WECHATY_PUPPET_SERVICE_TOKEN'] = token 修改为 os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = "127.0.0.1:9001" 本地运行报这个错

[WECHATY_PUPPET_SERVICE_TOKEN]仍然保留，就可以了
image

**Comment by nagaki09** [comment]
用wechaty，微信还是通过扫码登录服务端么？微信把我小号的扫码登录封了，能使用token么

**Comment by zwssunny** [comment]
我把wechaty 容器布置在公网上，在本地执行chagpt-on-wechat不显示二维码；用ding-dong-bot测试，二维码更新太快，来不及扫描，什么原因？

**Comment by yhfgyyf** [comment]
> 我把wechaty 容器布置在公网上，在本地执行chagpt-on-wechat不显示二维码；用ding-dong-bot测试，二维码更新太快，来不及扫描，什么原因？
如果使用的是padlocal协议，wechaty容器部署在公网后，
https://api.chatie.io/v0/hosties/puppet_padlocal_*** 这个会显示公网ip，
wechaty日志里会有你微信记录，
http://pad-local.com/#/login会显示你的微信已经登录。
手机微信上会显示已经登录ipad设备。

如果wechaty日志里有url，需要用微信扫码登录。

**Comment by austincityuwen** [comment]
> Pad协议教程
> 
> 1. [pad-local](http://pad-local.com/) 获取PadLocal Token
> 2. Python随机生成UUID：
>    import uuid;
>    print(uuid.uuid4());
> 3. Docker容器部署Padlocal网关服务(代码在最下方，替换
>    WECHATY_PUPPET_PADLOCAL_TOKEN 和 WECHATY_TOKEN为实际值)
> 4. 将uuid配置在config.json(对应KEY:wechaty_puppet_service_token)
> 5. 修改启动文件app.py
>    channel = channel_factory.create_channel("wxy")
> 
> *备注：
> 
> 1. Install：pip3 install wechaty
> 2. 配置文件 config.json 内的 **wechaty_puppet_service_token** 非[pad-local](http://pad-local.com/) 获取的Token，此处的token为uuid生成的，一定要将uuid生成的token和在pad-local获取到的token部署在Docker网关内！！！！
> 3. 判断环境是否存在问题，可以运行一下官方示例][ding-dong-bot.py](https://github.com/wechaty/python-wechaty/blob/master/examples/ding-dong-bot.py)，具体[中文文档](https://wechaty.readthedocs.io/zh_CN/latest/)。
> 4. 本地运行没有公网IP，需要将 **os.environ['WECHATY_PUPPET_SERVICE_TOKEN'] = token** 修改为 **os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = "127.0.0.1:9001"**
> 
> ```
> # 设置环境变量
> export WECHATY_LOG="verbose"
> export WECHATY_PUPPET="wechaty-puppet-padlocal"
> # PadLocal Token
> export WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal_xxx"
> 
> export WECHATY_PUPPET_SERVER_PORT="9001"
> # 可使用代码随机生成UUID：import uuid;print(uuid.uuid4());
> export WECHATY_TOKEN="d671a197-71c9-4ca6-a673-xxxxxx"
> # 由于版本细节问题，目前python-wechaty 支持最好的wechaty镜像为：[wechaty/wechaty:0.65](https://hub.docker.com/layers/wechaty/wechaty/0.65/images/sha256-d39b9fb5dece3a8ffa88b80a8ccfd916be14b9d0de72115732c3ee714b0d6a96?context=explore)
> docker run -ti \
>   --name wechaty_puppet_service_token_gateway \
>   --rm \
>   -e WECHATY_LOG \
>   -e WECHATY_PUPPET \
>   -e WECHATY_PUPPET_PADLOCAL_TOKEN \
>   -e WECHATY_PUPPET_SERVER_PORT \
>   -e WECHATY_TOKEN \
>   -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
>   wechaty/wechaty:0.65
> ```

如何在windows中连接padlocal的gateway，请大神出一期教程

**Comment by emmmnaadada** [comment]
> 

用token 7天未封号

**Comment by kadaliao** [comment]
> > 
> 
> 用token 7天未封号

有在微信群里密集发言吗？感觉这个操作比较危险。

**Comment by lsCoding666** [comment]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by lsCoding666** [comment]
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

arm的服务器不支持

**Comment by Gogoworks** [comment]
`15:57:20 VERB StateSwitch <WechatyReady> on(true) <- (true)
15:57:20 VERB StateSwitch <PuppetPadlocal> on(true) <- (pending)
15:57:22 VERB Message static load(1022852700664179636)
15:57:22 VERB Message constructor(1022852700664179636) for class WechatifiedMessage
15:57:22 VERB Message ready()
15:57:22 VERB Puppet messagePayload(1022852700664179636)
15:57:22 VERB Puppet selfId()
15:57:22 VERB IoClient onMessage(Message#Recalled[🗣Contact<阿园>])
15:57:22 VERB Puppet selfId()
15:57:22 VERB EventStreamManager grpcEmit(EVENT_TYPE_READY[23], {"data":"ready"})
15:57:22 WARN EventStreamManager grpcEmit(23, {"data":"ready"}) this.eventStream is undefined.
15:57:24 VERB Message static load(7249910975352019489)
15:57:24 VERB Message constructor(7249910975352019489) for class WechatifiedMessage
15:57:24 VERB Message ready()
15:57:24 VERB Puppet messagePayload(7249910975352019489)
15:57:24 VERB Puppet selfId()
15:57:24 VERB IoClient onMessage(Message#Recalled[🗣Contact<微信团队>])
15:57:24 VERB Puppet selfId()
`
启动docker wechaty:0.65 镜像，并微信扫描，最后出现这样的日志信息，请大佬帮忙看一下，哪里出了问题，应该如何解决？

**Comment by Gogoworks** [comment]
Snipaste_2023-03-24_00-02-10

附上日志截图 启动docker wechaty:0.65 镜像，并微信扫描，最后出现这样的日志信息，请大佬帮忙看一下，哪里出了问题，应该如何解决？

**Comment by lsCoding666** [comment]
> 

arm的用wechaty 1.11版本就行

**Comment by 726425219** [comment]
你好，我遇到了很难缠的问题，它导致bot不定时无响应，过一会儿又自动恢复
07:45:23 ERR [PadLocalClient] error while syncing onpush: VError: [tid:187eccbc] request has been cancelled for reason: CLIENT_ERROR: [tid:187eccbc] Exception while handling wechat request: long link send request timeout
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65)
在翻看PadLocal项目时发现作者对如上问题给了如下解答
Longlink host fail over has been added in wechaty-puppet-padlocal@1.11.14.
Please have a try and feedback is wecome.
所以想请问一下您的docker镜像里的wechaty-puppet-padlocal版本是什么，应该如何避免这个问题

**Comment by lsCoding666** [comment]
> 

0.65啊 而且只支持这个版本。我觉得你可能得从解决网络不好的角度考虑了，服务器是不是在国外？

**Comment by lsCoding666** [comment]
> 你好，我遇到了很难缠的问题，它导致bot不定时无响应，过一会儿又自动恢复 07:45:23 ERR [PadLocalClient] error while syncing onpush: VError: [tid:187eccbc] request has been cancelled for reason: CLIENT_ERROR: [tid:187eccbc] Exception while handling wechat request: long link send request timeout at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15) at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10) at Request. (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16) at Generator.throw () at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65) 在翻看PadLocal项目时发现作者对如上问题给了如下解答 Longlink host fail over has been added in wechaty-puppet-padlocal@1.11.14. Please have a try and feedback is wecome. 所以想请问一下您的docker镜像里的wechaty-puppet-padlocal版本是什么，应该如何避免这个问题

0.65啊 而且只支持这个版本。我觉得你可能得从解决网络不好的角度考虑了，服务器是不是在国外？

**Comment by 726425219** [comment]
> > 你好，我遇到了很难缠的问题，它导致bot不定时无响应，过一会儿又自动恢复 07:45:23 ERR [PadLocalClient] error while syncing onpush: VError: [tid:187eccbc] request has been cancelled for reason: CLIENT_ERROR: [tid:187eccbc] Exception while handling wechat request: long link send request timeout at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15) at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10) at Request. (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16) at Generator.throw () at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65) 在翻看PadLocal项目时发现作者对如上问题给了如下解答 Longlink host fail over has been added in wechaty-puppet-padlocal@1.11.14. Please have a try and feedback is wecome. 所以想请问一下您的docker镜像里的wechaty-puppet-padlocal版本是什么，应该如何避免这个问题
> 
> 0.65啊 而且只支持这个版本。我觉得你可能得从解决网络不好的角度考虑了，服务器是不是在国外？

服务器在新加坡，因为chatgpt-on-wechat 适合架在境外，有没有什么好的建议，大佬

**Comment by lsCoding666** [comment]
> 

issue里面有墙内部署的教程 就用自家windows电脑跑就行了，简单来说就是cloudflare workers反代或者是用腾讯云函数之类的反代

**Comment by 726425219** [comment]
> > 
> 
> issue里面有墙内部署的教程 就用自家windows电脑跑就行了，简单来说就是cloudflare workers反代或者是用腾讯云函数之类的反代

加个微信私聊，大佬，AIYLWL

**Comment by 726425219** [comment]
> > 
> 
> issue里面有墙内部署的教程 就用自家windows电脑跑就行了，简单来说就是cloudflare workers反代或者是用腾讯云函数之类的反代

你是在国内部署的吗？没有遇到这个问题吗

**Comment by JinLiGame** [comment]
wechaty的免费web协议有人用过吗？封号的几率怎样？怎么使用web协议？

**Comment by zwssunny** [comment]
web协议没成功，wechaty不稳定，放弃了。



---Original---
From: ***@***.***&gt;
Date: Mon, May 22, 2023 17:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhayujie/chatgpt-on-wechat] add wechaty (PR #244)




 
wechaty的免费web协议有人用过吗？封号的几率怎样？怎么使用web协议？

**Comment by yhfgyyf** [comment]
> wechaty的免费web协议有人用过吗？封号的几率怎样？怎么使用web协议？

我用过wechaty，好像还蛮稳定，7天免费，超过7天收费，还蛮贵的，有这钱不如上微信公众号，云服务器费用算上都没这个贵

**Pull request merged**
