### PR TITLE
feat: support gemini model

### PR DESCRIPTION
**Pull request by zhayujie**

### CODE REVIEW

**Comment by zhayujie** [comment]
目前使用的是 gemini-pro 模型，实测下来回复还不稳定，并且对敏感词判断十分严格，可以先作为测试体验使用。

**Comment by zhayujie** [comment]
### 使用方法

1.安装依赖
pip3 install google-generativeai

2.配置api key
`config.json` 中增加 `gemini_api_key`  配置，从官网获取

3.model修改
model配置 改为 `gemini` 或者使用 `#model gemini` 切换

**Comment by wxfaith** [comment]
> ### 使用方法
> 1.安装依赖 pip3 install google-generativeai
> 
> 2.配置api key `config.json` 中增加 `gemini_api_key` 配置，从官网获取
> 
> 3.model修改 model配置 改为 `gemini` 或者使用 `#model gemini` 切换

按照这个设置了依旧无法使用，很多google.开头的库都在报错，python3.9.12, mac上运行

**Comment by wxfaith** [comment]
> ### 使用方法
> 1.安装依赖 pip3 install google-generativeai
> 
> 2.配置api key `config.json` 中增加 `gemini_api_key` 配置，从官网获取
> 
> 3.model修改 model配置 改为 `gemini` 或者使用 `#model gemini` 切换

[ERROR][2023-12-16 00:06:26][chat_channel.py:299] - Worker return exception: bases must be types
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/wangxiang/Downloads/chatgpt-on-wechat-master/channel/chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "/Users/wangxiang/Downloads/chatgpt-on-wechat-master/channel/chat_channel.py", line 189, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/Users/wangxiang/Downloads/chatgpt-on-wechat-master/channel/channel.py", line 37, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/Users/wangxiang/Downloads/chatgpt-on-wechat-master/bridge/bridge.py", line 64, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/Users/wangxiang/Downloads/chatgpt-on-wechat-master/bridge/bridge.py", line 55, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "/Users/wangxiang/Downloads/chatgpt-on-wechat-master/bot/bot_factory.py", line 52, in create_bot
    from bot.gemini.google_gemini_bot import GoogleGeminiBot
  File "/Users/wangxiang/Downloads/chatgpt-on-wechat-master/bot/gemini/google_gemini_bot.py", line 10, in <module>
    import google.generativeai as genai
  File "/usr/local/lib/python3.9/site-packages/google/generativeai/__init__.py", line 45, in <module>
    from google.generativeai import types
  File "/usr/local/lib/python3.9/site-packages/google/generativeai/types/__init__.py", line 17, in <module>
    from google.generativeai.types.discuss_types import *
  File "/usr/local/lib/python3.9/site-packages/google/generativeai/types/discuss_types.py", line 21, in <module>
    import google.ai.generativelanguage as glm
  File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage/__init__.py", line 21, in <module>
    from google.ai.generativelanguage_v1beta.services.discuss_service.async_client import (
  File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/__init__.py", line 21, in <module>
    from .services.discuss_service import DiscussServiceAsyncClient, DiscussServiceClient
  File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/__init__.py", line 16, in <module>
    from .async_client import DiscussServiceAsyncClient
  File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/async_client.py", line 31, in <module>
    from google.api_core import exceptions as core_exceptions
  File "/usr/local/lib/python3.9/site-packages/google/api_core/exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
  File "/usr/local/lib/python3.9/site-packages/google/rpc/error_details_pb2.py", line 21, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 30, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
报错信息如上

**Comment by Simonmxy** [comment]
[INFO][2023-12-17 18:31:41][wechat_channel.py:194] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
模型设置为: gemini), receiver=@4cda57e5b8dbe99f1deffc21a85eb2faee6d464aeeff6f7b641572ec040c27c4
[INFO][2023-12-17 18:31:44][bridge.py:49] - create bot gemini for chat
[INFO][2023-12-17 18:31:45][google_gemini_bot.py:33] - [Gemini] query=Hi
[ERROR][2023-12-17 18:31:54][google_gemini_bot.py:45] - [Gemini] fetch reply error, may contain unsafe content
[ERROR][2023-12-17 18:31:54][google_gemini_bot.py:46] - Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.

需要ADC吗？

**Comment by Smithcaige** [comment]
你们不提示吗[INFO][2023-12-20 16:45:12][google_gemini_bot.py:33] - [Gemini] query=hello
[ERROR][2023-12-20 16:46:11][google_gemini_bot.py:45] - [Gemini] fetch reply error, may contain unsafe content
[ERROR][2023-12-20 16:46:11][google_gemini_bot.py:46] - Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2404:6800:4012:4::200a%5D:443: Failed to connect to remote host: FD Shutdown

**Comment by zy-zhangyu** [comment]
如何解决?

**Comment by Huangqiankun** [comment]
> [INFO][2023-12-17 18:31:41][wechat_channel.py:194] - [WX] sendMsg=Reply(type=INFO, content=[INFO] 模型设置为: gemini),receiver=@4cda57e5b8dbe99f1deffc21a85eb2faee6d464aeeff6f7b641572ec040c2 7c4 [INFO][2023-12-17 18:31:44][bridge.py:49] - 创建聊天机器人 Gemini [INFO][2023-12-17 18:31:45][google_gemini_bot.py:33] - [Gemini] query=Hi [错误][2023-12-17 18:31:54][google_gemini_bot.py:45] - [Gemini] 获取回复错误，可能包含不安全内容 [错误][2023-12-17 18:31:54][google_gemini_bot.py:46] - 未找到您的默认凭据。要设置应用程序默认凭据，请参阅https://cloud.google.com/docs/authentication/external/set-up-adc了解更多信息。
> 
> 需要ADC吗？

这个你解决了么？我也遇到这个问题了

**Comment by Timelose** [comment]
> [INFO][2023-12-17 18:31:41][wechat_channel.py:194] - [WX] sendMsg=Reply(type=INFO, content=[INFO] 模型设置为: gemini), receiver=@4cda57e5b8dbe99f1deffc21a85eb2faee6d464aeeff6f7b641572ec040c27c4 [INFO][2023-12-17 18:31:44][bridge.py:49] - create bot gemini for chat [INFO][2023-12-17 18:31:45][google_gemini_bot.py:33] - [Gemini] query=Hi [ERROR][2023-12-17 18:31:54][google_gemini_bot.py:45] - [Gemini] fetch reply error, may contain unsafe content [ERROR][2023-12-17 18:31:54][google_gemini_bot.py:46] - Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
> 
> 需要ADC吗？

这个问题解决了吗，我也遇到了同样的问题

**Comment by liuyilook** [comment]
我也遇到这个问题了

**Comment by lwg712176** [comment]
这个问题困扰我很多天了，代理改成PAC模式，"proxy": "http://127.0.0.1:10813",也改了无数次，curl我的api也可以成功，访问网页也是正常的，不知道哪里的问题，有大佬遇到过吗
[INFO][2024-03-19 09:48:43][bridge.py:51] - create bot gemini for chat
[INFO][2024-03-19 09:48:44][google_gemini_bot.py:28] - [Gemini] query=你是谁
[ERROR][2024-03-19 09:50:29][google_gemini_bot.py:40] - [Gemini] fetch reply error, may contain unsafe content
[ERROR][2024-03-19 09:50:29][google_gemini_bot.py:41] - HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Max retries exceed
ed with url: /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (Caused by NewConnectionError('<urllib3.connection.HTTPSCo
nnection object at 0x06799A78>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接
尝试失败。'))
[INFO][2024-03-19 09:50:29][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
invoke [Gemini] api failed!), receiver=@1308abaf396fc88bfcde1ffb1423718315fa7c62d3eb12eca390e433c743ba1c
[INFO][2024-03-19 09:50:38][app.py:19] - signal 2 received, exiting...
[INFO][2024-03-19 09:50:38][config.py:214] - [Config] User datas saved

**Pull request merged**
